name: Supabase Sync & DB Migration

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'
      - '.github/workflows/supabase-sync.yml'
  workflow_dispatch:

jobs:
  deploy-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project & Push Database Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: "dednimurwcqiitrairsm"
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID --password "$SUPABASE_DB_PASSWORD"
          supabase db push --password "$SUPABASE_DB_PASSWORD"
